#!/bin/bash

# Author: Sergio Chaves Garcia-Mascaraque
# Swansea, Wales, United Kingdom
# Proyecto iniciado en Octubre de 2018

# This script is a modification of the previous gnp2tex
# Now it just relies on gnuplot commands, not latex

print_usage() {
    printf  "Usage: Script to transform gnuplot plots into pdf with LaTeX
       standalone content.

       Usage:
           gnp2tex -f fileName.gn \\\\
                   -s myPDF.pdf \\\\
                   -p '\\\\usepackage{myPackage};\\\\usepackage{myOtherPackage}\\...'

       Args:
           -h: Print help.
           -f: Gnuplot file to be compiled into pdf.
           -s [Optional]: Name of the pdf output. If not provided, the name
                          will be the name of the file ending with .pdf
           -p [Optional]: LaTeX packages to be included in the compilation.\n"
}

while getopts 'f:s:p:h' flag; do
    case "${flag}" in
        f) nameGnuplot="${OPTARG}" ;;
        s) savePDF="${OPTARG}" ;;
        p) packages="${OPTARG}" ;;
        h) print_usage exit 1;;
    esac
done

if [ -z "${nameGnuplot}" ]; then
    echo "ERROR: Name of the file (-f) argument is not provided."
    exit 1
fi

echo "
# Set the terminal to produce the latex results
set terminal lua tikz standalone size 20cm,14cm

# Set the margins in the figure
set tmargin at screen 0.90
set bmargin at screen 0.10
set rmargin at screen 0.95
set lmargin at screen 0.10

set output 'temp.tex'
" > ./wrapper.gn

# Copy the gnuplot script into the wrapper file
cat ${nameGnuplot} >> ./wrapper.gn

# Produce the figure file
gnuplot ./wrapper.gn

# Include packages inside the file
if [ "${packages}" ]; then
    lineApp=$( grep -nr 'usepackage\[active,tightpage\]{preview}' temp.tex | \
               cut -d : -f -1 )
    # # Format by lines
    packages=$( echo $packages | tr ";" "\n" )
    auxVar="1"
    for comm in ${packages[@]}
    do
        line=$(( $lineApp + $auxVar ))
        sed -i "${line}i\\\\${comm}" temp.tex
        auxVar=$(( $auxVar + 1 ))
    done
fi

# Produce the pdf file
pdflatex ./temp.tex

if [ -z "${savePDF}" ]; then
    pdfName=$( echo ${nameGnuplot} | sed 's/.gn/.pdf/g'  )
else
    pdfName=${savePDF}
fi

mv ./temp.pdf ${pdfName}

# Remove unwanted files
rm ./wrapper.gn
rm temp.aux
rm temp.gnuploterrors
rm temp.tex
rm temp.log
rm temp-gnuplottex*
